image: golang:1.11.4

variables:
  REPO_NAME: github.com/mendersoftware/mender-stress-test-client

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build
  - publish

test:format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - mender-stress-test-client

publish:binary:
  stage: publish
  dependencies:
    - compile
  script:
    - echo "publish mender-stress-test-client binary to s3 here"